# name: hrms_mobile_application
# description: "A new Flutter project."
# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: ">=3.10.4 <4.0.0"

# dependencies:
#   flutter:
#     sdk: flutter

#   cupertino_icons: ^1.0.8
#   http: ^1.2.0
#   shared_preferences: ^2.2.2
#   intl: ^0.19.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^6.0.0

# flutter:
#   uses-material-design: true

#   assets:
#     - assets/images/







name: hrms_mobile_application
description: "A Flutter HRMS mobile application for task management"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Uncomment if you have assets
  # assets:
  #   - assets/images/